name: test-ci

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (if script exists)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script – skipping."
          fi

      - name: Unit tests (if script exists)
        run: |
          if npm run | grep -q "test"; then
            npm test --if-present
          else
            echo "No test script – skipping."
          fi

      - id: build
        name: Build (if script exists)
        run: |
          if npm run | grep -q "build"; then
            npm run build --if-present
          else
            echo "No build script – skipping."
          fi

      - name: Archive production-ready build
        if: success() && (steps.build.outcome == 'success' || steps.build.outcome == 'skipped')
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/
            server/dist/
          if-no-files-found: ignore